import { useEffect, useState } from "react";
import { Save, UserRound } from "lucide-react";
import { getMe } from "../../api/auth.api.js";
import { updatePublicProfile } from "../../api/freelancer.api.js";

const FreelancerMyProfile = () => {
  const [user, setUser] = useState(null);
  const [form, setForm] = useState({ name: "", title: "", bio: "", location: "", hourlyRate: "", avatar: "", skills: "" });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  useEffect(() => { getMe().then((data) => { const u = data.user || data; setUser(u); setForm({ name: u.name || "", title: u.title || "", bio: u.bio || "", location: u.location || "", hourlyRate: u.hourlyRate || "", avatar: u.avatar || "", skills: Array.isArray(u.skills) ? u.skills.join(", ") : "" }); }).catch((e) => setError(e?.response?.data?.message || e?.message || "Failed to load profile")).finally(() => setLoading(false)); }, []);
  const save = async () => { try { setSaving(true); setError(""); const data = await updatePublicProfile(user.id, { ...form, hourlyRate: Number(form.hourlyRate) || 0, skills: form.skills.split(",").map((x) => x.trim()).filter(Boolean) }); setUser(data.user || data); setMessage("Profile updated successfully."); } catch (e) { setError(e?.response?.data?.message || e?.message || "Failed to update profile"); } finally { setSaving(false); } };
  if (loading) return <div className="p-10 text-center text-sm text-slate-500">Loading profile...</div>;
  return <div className="mx-auto max-w-5xl space-y-6"><div><h1 className="font-serif text-3xl font-bold text-slate-900">My Profile</h1><p className="mt-1 text-sm text-slate-500">Manage the profile clients see.</p></div>{error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-600">{error}</div>}{message && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}<div className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><div className="flex items-center gap-5 border-b border-slate-100 pb-6">{form.avatar ? <img src={form.avatar} alt={form.name} className="h-20 w-20 rounded-full object-cover" /> : <div className="flex h-20 w-20 items-center justify-center rounded-full bg-indigo-100 text-indigo-600"><UserRound className="h-8 w-8" /></div>}<div><h2 className="font-serif text-2xl font-semibold text-slate-900">{form.name || "Freelancer"}</h2><p className="text-sm text-slate-500">{user?.email}</p></div></div><div className="mt-8 grid gap-6 md:grid-cols-2">{[["name","Name"],["title","Professional Title"],["location","Location"],["hourlyRate","Hourly Rate"]].map(([name,label]) => <div key={name}><label className="mb-2 block text-sm font-semibold text-slate-700">{label}</label><input name={name} value={form[name]} onChange={(e) => setForm({ ...form, [name]: e.target.value })} className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-indigo-500" /></div>)}<div className="md:col-span-2"><label className="mb-2 block text-sm font-semibold text-slate-700">Avatar URL</label><input value={form.avatar} onChange={(e) => setForm({ ...form, avatar: e.target.value })} className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-indigo-500" /></div><div className="md:col-span-2"><label className="mb-2 block text-sm font-semibold text-slate-700">Skills</label><input value={form.skills} onChange={(e) => setForm({ ...form, skills: e.target.value })} placeholder="React, Node.js, UI/UX" className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-indigo-500" /></div><div className="md:col-span-2"><label className="mb-2 block text-sm font-semibold text-slate-700">Bio</label><textarea rows={6} value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} className="w-full resize-none rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-indigo-500" /></div></div><div className="mt-8 flex justify-end"><button onClick={save} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-6 py-3 text-sm font-semibold text-white hover:bg-indigo-700 disabled:opacity-50"><Save className="h-4 w-4" />{saving ? "Saving..." : "Save Profile"}</button></div></div></div>;
};
export default FreelancerMyProfile;
